### ISSUE TITLE
Original logger name is lost

### ISSUE THREAD

**Issue by eric239** [stackify/stackify-log-logback#2]
When the logs reach Stackify, the original logger name (i.e. `com.foo.MyClass`) is lost and nowhere to be found. This prevents a rather useful filtering approach and can cause confusion when viewing. All messages appear to have `"logger": "stackify-log-logback-1.1.6"`

**Comment by eric-martin** [comment]
We capture the class name and method of the log message. If you toggle the 'Code Source Method' field, you will be able to see the logging method and if you hover over it, you will also be able to see the class name.

**Comment by eric239** [comment]
Thanks for the follow-up.

Firstly, source method (and class) is different from the logger name. It is customary to use FQN for the latter, but not a rule/requirement. Having the actual logger name available is still important.

Secondly, having toggled `Code Source Method` field I still have to select a specific log line and open the document in order to view it. And I am not able to match on class name using full text search, e.g. trying something like `MyClass` or `*MyClass*` or `/.*MyClass.*/` doesn't find anything (and I know there're lines produced by `com.mycompany.MyClass`)

So I think both the lack of real logger name data and inability to easily search by class name (if not logger name) should both be addressed.

**Comment by eric-martin** [comment]
I'll log two tickets for the development team to get prioritized and fixed.
1) Capture logger name
2) Improve search UI (with your MyClass scenario as a specific example)

**Comment by shvez** [comment]
is there any progress on this issues? We are intersted in having Logger name too

**Comment by eric-martin** [comment]
We haven't made any progress on this, but I've confirmed that this item is still on our backlog.
